language: scala

scala:
   - 2.11.8
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - testing

addons:
  postgresql: "9.4"

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

before_script:
  - cd ./hat-database-schema
  - source ./env.sh
  - bash ./setupDatabase.sh
  - bash ./setupAccess.sh
  - bash ./applyEvolutions.sh -c structuresonly data
  - cd ../
  - sed -e "s;%DATABASE%;$DATABASE;g" -e "s;%DBUSER%;$DBUSER;g" -e "s;%DBPASS%;$DBPASS;g" deployment/database.conf.template > src/main/resources/database.conf
  - cp ./src/main/resources/database.conf ./codegen/src/main/resources/database.conf

script:
   - sbt clean
   - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
   - sbt coverage "testOnly hatdex.hat.api.*" -Dconfig.file=src/main/resources/application.test.conf

after_success:
  - sbt coveralls
