language: scala
dist: trusty
sudo: false
scala:
  - 2.12.4
jdk:
  - openjdk8

services:
  - docker
  - memcached
addons:
  postgresql: "9.5"

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

notifications:
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "Build %{commit}: %{commit_message}"
    rooms:
      secure: f10x2/Uu8gyami/QGXS4dVOehWAY9mAKWYchs6Wr92qgnCPW1ALpoZlRqQiVvjsjcByxjLuVz0NgUFT7RmPusV3OuVLpBetjb6J+55kWebhdAE7OlAhGgmhxLcdWFvBuql4hhN7GHfUNQv0wwabAHoiq/cbMC9uZYcJDdfznqAjSZvlb4t6zgGhNyCFJL0v1nTdJz64zo2SEUdwWFhaV7/k0wbpTjFytyySj0LVW5ymkApQD+Lqvn2KZBDMwtwrMH8derLLrqbj41UB7EsnGP4K7hh6HUOgf4aw2r46m/wFqTmwzgeD140iWslmDISprhSW2WAo5QG8hz0rKuywzHL/NB2WmRMF7Dg6tnG0zihVy+fJJ7CviVewC6DWUtHGZYENX6BNVImymAdVu2LIh+QrHUEjXlPRjBdH97ZEnSzc/RKIvVBRzyMZ5IAv4wZCuKHthPeTX17ZCp3mnL3BD/kXacabao0H0ot1fPaDBErmA5cp0STPh2OmPheKElLDoFHyXubeMPpicXTUkeFqnYTtrdLRgC+XvvHQegNkUO/rq/62BwC6ewSA7udHOj7w8fG9mSpOcEAsDbL7FOiqw64NVWMrTtWq0KaVyC+KESpaPgHWapbs9HCEFKdwtj+pygvilVDvqQDlp4KINYAhJynmATneh3T9Qa2Z2Juqrayw=

branches:
  only:
    - master
    - testing
    - dev

# Handle git submodules yourself
git:
    submodules: false

env:
  global:
    - RUMPEL_BUCKET=frontend-build-artifacts
    - AWS_DEFAULT_REGION=eu-west-1
    - secure: XlVGwMwoqwE8xuIZN6Q/kIDtkW2yAtiBD0guErvOhLM9sgZUpZ740uX8ZgcJKOkEYntTPcItROubVSU5Ho3575AIv1ddLSDqZR6oVeBsFI/dLzqkppISSRAv3xBKjBx5kprqdAAJkMbXEww651pfNbScH9ffy1FKHend2hzVYEh1sLF7E+/Qr+oI8Oned20Tqn+pSpln/bVzR8tIzlRs4YgVuttzwgScgSwnGKmlO20Rnc8NJDCTby/C5J7k+jLnmHKDmccy3H+VkgVLep3bjc+yqSBGREhZWlhr3kNmA5WVRADlXnaz4xr+uu6RdqN88m/LJvCNbjpkd+8K8J98I9ldAbQ26sgWbsdQAGiN1SKsw1DXbgtYewlvWp0sroLF2Llbz0f/YBM4f2WnRq44XU6/Apfa6+eK3fHSuRIhpzodO806rNzFbV6rwl/UYXaEAtFWUJl+qkpp3/Nz4xQRB51yZEOTYNOg7xVQc/69/3v5oO9lDkaAIKoCnf+aD/ZwxW4kFa/DG79eHZmmQd+Q2MRFVv2NSg1orCMO+zBACiToZfDxh/nH0//P333xyiDZ3TB35ls7i6gxi5fJmYcPne1IxQarbvJOu+Qs2bpK/6CwyGF4yc5jpaZw2mWe4JHPzmJ0YboUK+mp++5fBnvoUC7hawlWrtMkxCxM/IVHiKQ=
    - secure: szpRbKNtbqthtOMMe1ti+HBHPkhxKkqhylp3pz89ICi15f/7d4XN7ckWRmO5GW/LNlukIrSDZqnXU84U9FVK9HryVUlTy/CkKAxVtWWhosc7E/Q9IEOtEBeM4rCCXNzwc1yJos+qZYq3lZQQaVbG3Qwrw3zp16JFnr9pc+AhpEEgLvA1tAd/rTWzJSnHE1irtZQE3WZoJiKwCyrCjrUaMdXCs9lz5peCQChfjiutN2C6Q9rQW1i7nBdnmrRrs6InK3btUVsaEerH0fTncEphydiLuRZ468t1ikO1zqR/ZRo/os3o9BnuNVJLIEARlc0UjAxh53/77K+gW2m7DcJvO6wPnf4ogB8MMrNdCH7gZzMKOzP2ljthj5KEZFpQxtqVpIsAaA8rln/uyHCXojM8GDbUeJBpbQoVY041HseG5qMawbRvmoyIjW/PFdu61tlxz5BZLp9XjAD6tRiwOD6IFZXhxhikFs/hL6xTEaJPDjiU2wzuVp5l1mi3kg3lOyAg5MOpoy+2Ri8jx0cFkjyKD1WOAonQ8yei33ELPcCNufvvoy5qlaE2P0Fttcd8kxq1JfdTSdWEmp8FFaL7u0w5KXNJC85HQkNQhTlsHlGEmkPiIYzQ9Hq0EhTmsfRCKTlBaZX6yMmpNitX0AjlVzV/esYrVJprYUvGDSR25cE1KrQ=
    - secure: USVpIy0emFH9ZvrkckuOxF3a9SsWOnH5a8XqZ/5WcA8xT+Jk3MDk8f1upx4DBpa4V4DRxI7Cvr326cP/Xi2gsBmgaKneo1tjACExIy42R9YZ8XPdr1Bbng7LDO4xfNSrKwMBUOeA1vF9/yZU4ki0Fv/J5wLYCthpnfEQ7+mubZ9h4dzFv0hd1wAinFR0vTVAn3+dQ4jaZSU9Tl/0L5T7y2Z2v/m9c4PHkII38WwdIvkrdY2jmSm0eSD7iEIwv3UwYk9BTIknmdHYfQ7xx256tRkadgMThmhdJhdm6JaLr819fXe30u/OIH15hLyM4ND+FjW6DvKNs3+2AVT7uOSK/wRntA2Fwvpczq7cwMxi2mU4HXXzH7a82Iswnm8Nn6Od+9vxsRV3nyl8XLmkn8Gn03k6+Pr2jj/ljdvGYeFmMYcvSlskE6VbWBGxyu6vAjccnUtGK9r3lkoxjX8CgiCev+/fwX5jlWvTSVeS8bvGy7dlRQQ2XRscQ8av5fKcACZOJVpQ4YgKnQ8j4MDUfT6sJ/8kONwXu4d6f9AREazZEml5taKvkZuDpHWPr77SqG+9Fccybm8IWjr0uq1eR+URsKJAXWj7ah0a7qA4M8WikH0FePR79YyyF2APm8KtDe7ZsbkbMdjVngrRhpACCUtsGLPhX4Y62szoBY8SzYJV/LI=
    - secure: garvO7sZMrDyhJ/LroK5SlidZCCBRa868Ebmuwwv75vlqeablbQk0LKEFqk6WjO428TIsu+JT0fkrg8eVoJPYO1n6/GhjtI9R4TgRNWcsoaFZe1RdCJkZoJemaeXkDomq34ZKRwnl7QsWeKInqtwDl3EJwoALaQjPPXEsrO20uodLKD8zFhCf89uQ4HIW6kAXJHTQSXByjkuRenhnyQ4nM/ixLnHZ+auJ/NG2RFUPADxRjpTNWcKoqvVh7QGzvYCiahDSaY669bZnLmTzOMH1EtVf8UPDFyHM56Pgq3a/OdOU4sxhSIdf3C+pbD8XV4lmU3gE/OLbybkk87YsU4J5iZLr552Dkm+g0ak2AnF4lxQwzm0sN/Q76eZRGpcBacncCLRlLK1kmWlfoJ6RrQTPRMBmNIzveCZ9gSY49AWEMUSn7ZG9F+MxCYnVAWlWDAEhKfQLYpHACa/GbGgvBaek6wG8vaeTMeBEVunpb3lsgQJ7fNBVtQ4vcn++0be1kW3+bAmPlviDJ+myey2O2uk1f5/T3k0s7UhbFcTzfN7HJ+2eIpg1Hp0FbmVEJvZVmE6TE8tiF0UwAJzbKDeU2HwGg8dXBbpKn/GWm70R1yytOCls4Mmndfxq75tnh9/ZRK7ihpa+TDg/xAjWqREGo1nHhObmY5L3rWxptyWKPgdVeA=

matrix:
  include:
    - env:
      - REPOSITORY_NAME=hubat
      - RUMPEL=sandbox
      - ALT_RUMPEL=sandbox-react
    - env:
      - REPOSITORY_NAME=hubofallthings
      - RUMPEL=live
      - ALT_RUMPEL=live-react
      - secure: "QrIhQCkVPMH6B+eKbdIRqpDyXyTS+SEJyQ3pz1GrrFipneQDZrwDj6VmYf00ebo1flNgEY/D/si1KoXk3NMfz3P9+3VzXzFOO4vjh2GShWJpvlSoo9FC31eSy2wCbtC7FVwOWn36200G2YL0UVVVG1vv+Sbto4Y8JUl/WahOoFix8R6v1ttyhnpVfknmTpxY/03btVdYkq03Yh9xqsMaAblATYvm1ApV/owy1FtfxY6Ykxwtd+aj0tnTAknJjAfk3irZXDQmLb6uGNPTH2YoijesdxpCq/YZhbUXEMQ+4YMGR9YU+3vR0gv65LGYk3+cdSn0teoDu6liiUxB80PKPEScyk68jfkfUvqDT0ODig02fKgVGi6QCQ2kcRFWEhZqlyHlO2UDndb4j632Zf+cwpPF4WZWoyN4BSgpeLM7VzpEYn4HF4MCLusya1feYe0Mn0gzLtTMaXu+K8c5OAqkyC3jKZBSFX98H2xNfpbrpV0op60QwY3Td7j7vd8q5b1/lub2xB3w/erfAs0wwVBfUbwVZrOFTMDt101t+hNAQBxqYHzP/6NhmfNizl/67erNQO+vMdeKqls6jKb0U/jvrkB4DiaIDuajUMHJKWh96SFKgeMjLQKKUlvNTBwJcULDeKio+vVdv1K3xLcS/MyzvoTPv7VjuAqYEv6JITtd0dk="
      - secure: "HuEUJ12CGLphVWHMHRK6IHOb2mGUqDlojzM6swozu6ceGAm2PlHUZm6SkdkvhAWq7sonjpnQKEC/42olocxSBi6SPOkHrWxIQMPTODr84XLI4gsyw9yh2eGENfYF0vyRTB4u8MbsJ0RvwEyyTzWNrmxeIsvVudYAsXGWfR1L/WA4J7luyGHeJ+ce96ZhKE5wJz67hPIzkOY2A/pkUdrrV8K+aObg+MZz9KdMl4g1S/nFNDIMwvB1VRzJ8kPkukcOkMN/t0uBXJT9YJZWfgTvHRhZJSkHkaMCAq3h0fYUeHDH1n4Dyir8VWuHW1NkEtF6yaLF6WA2Wa9Y1+Ucw4ANYrwgSy3Bu1kd06xwmbMTo/iVzL18I/2N7dj4s64mvsHkpf6YM1aBXoT+8GS4sjB/1NIAfGOi/dl5jjJKk5rkA9K89BmStUW737LbLADL0148aUrn5tNSsP2BoSKTjRSgqbBpsyH51ids7GqSOb0CKemibcAGaIGnzXza68cQgFnwAk6WIehukBeH7e+bGudhVDIuO+AIEVclHkOTDr3a8jxDqpEspqdSYAx+3J0K3zBbVqkkg2Ouj6AM4p9hA72SEWLulThZfGIP77Lv2VJvnrdCMUmZ5k8j/Zv6itd+9dR07vOH+Iq0Z/o6wIVBogyxBdMR6K+LInIeyp0aJAFNFqM=" 


# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

# Set up test database and user
# Copy the frontend assets from S3 to the right location
before_script:
  - psql -c "CREATE DATABASE testhatdb1;" -U postgres
  - psql -c "CREATE USER testhatdb1 WITH PASSWORD 'testing';" -U postgres
  - psql -c "GRANT CREATE ON DATABASE testhatdb1 TO testhatdb1" -U postgres
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" || -z "$RUMPEL" ]]; then
      cd ./hat/app/org/hatdex/hat/phata/assets/
      aws s3 cp s3://${RUMPEL_BUCKET}/${RUMPEL} rumpel --recursive
      aws s3 cp s3://${RUMPEL_BUCKET}/${ALT_RUMPEL} alt-rumpel --recursive
      cp rumpel/*.js* js/
      cp rumpel/*.css stylesheets/
      gzip --keep --force js/*.bundle.js
      cp -r rumpel/assets/* .
      cp -r alt-rumpel/* .
      rm -r rumpel
      rm -r alt-rumpel
      cd -
    fi

script:
  - make clean # sbt clean
  - make prod # sbt ++$TRAVIS_SCALA_VERSION compile
  - |
    if [[ "$REPOSITORY_NAME" = "hubat" ]]; then
      # TODO: Update test next
      sbt ++$TRAVIS_SCALA_VERSION test:compile
      sbt ++$TRAVIS_SCALA_VERSION "project hat" coverage test -Dconfig.file=hat/conf/application.test.conf
    fi
  - make docker-prod # sbt -Denv=prod docker:stage
  - docker build -t ${REPOSITORY_NAME}/hat:$(git rev-parse --short HEAD) hat/target/docker/stage

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" || -z "$RUMPEL" ]]; then
      sbt coverageReport && sbt coveralls
    fi

before_deploy:
  - unset AWS_SECRET_ACCESS_KEY;
    export AWS_SECRET_ACCESS_KEY=$DEPLOY_AWS_SECRET_ACCESS_KEY;
    unset AWS_ACCESS_KEY_ID;
    export AWS_ACCESS_KEY_ID=$DEPLOY_AWS_ACCESS_KEY_ID;
    ECR_REPOSITORY=$(aws ecr describe-repositories --repository-name ${REPOSITORY_NAME} --query 'repositories[0].repositoryUri' --output text);
    eval $(aws ecr get-login --no-include-email)
  - docker tag ${REPOSITORY_NAME}/hat:$(git rev-parse --short HEAD) ${ECR_REPOSITORY}:$(git rev-parse --short HEAD)

deploy:
  - provider: script
    script:
      - docker push ${ECR_REPOSITORY}:$(git rev-parse --short HEAD)
    skip_cleanup: true
    on:
      repo: Hub-of-all-Things/HAT2.0
      branch: dev
  - provider: script
    script:
      - docker push ${ECR_REPOSITORY}:$(git rev-parse --short HEAD)
    skip_cleanup: true
    on:
      repo: Hub-of-all-Things/HAT2.0
      branch: master
