language: scala

scala:
   - 2.11.8
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - testing
    - dev

addons:
  postgresql: "9.5"

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

script:
   - sbt clean
   - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
   - sbt coverage "testOnly hatdex.hat.api.*" -Dconfig.file=src/main/resources/application.test.conf

after_success:
  - sbt coveralls
