language: scala

scala:
   - 2.11.6
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - testing

addons:
  postgresql: "9.3"

before_script:
  - cd ./hat-database-schema
  - bash ./env.sh
  - bash ./setupDatabase.sh
  - bash ./setupAccess.sh
  - bash ./applyEvolutions.sh
  - cd -

script:
   - sbt clean
   - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
   - sbt coverage "testOnly hatdex.hat.api.*" -Dconfig.file=src/main/resources/application.test.conf

after_success:
  - sbt coveralls
