language: scala

scala:
   - 2.11.6
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - testing

addons:
  postgresql: "9.3"

before_script:
  - bash ./hat-database-schema/env.sh
  - bash ./hat-database-schema/setupDatabase.sh
  - bash ./hat-database-schema/setupAccess.sh
  - bash ./hat-database-schema/applyEvolutions.sh

script:
   - sbt clean
   - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
   - sbt coverage "testOnly hatdex.hat.api.*" -Dconfig.file=src/main/resources/application.test.conf

after_success:
  - sbt coveralls
