version: "3"

services:

    database:
        image: hubofallthings/hat-postgres:latest
        expose: ["5432/tcp"]
        networks: ["sandbox"]
        environment:
            - POSTGRES_USER=master
            - POSTGRES_PASSWORD=pa55w0rd

    hat_server:
        image: hubofallthings/hat:v2.6.6
        ports: ["9000:9000", "9001:9001"]
        networks: ["sandbox"]
        volumes:
            - .:/code
        depends_on:
            - database
        environment:
            - DB_USER=master
            - DB_PASSWORD=pa55w0rd
            - DB_HOST=database

networks:
    sandbox:
        driver: bridge
