 TableValues:
    description: Data Table information with structure and values filled in - related fields and sub-tables
    allOf:
    - $ref: '#/definitions/TableStructure'
    - properties:
        fields:
          type: array
          description: Array of fields (columns) in the table
          items:
            $ref: '#/definitions/FieldValues'