swagger: '2.0'
info:
  version: 2.0.0
  title: HAT 2.0 API
host: api.hubofallthings.com
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:

/ApiBundleTable:
    post:
      description: |
        Creates a new Bundle Table
      parameters:
        - name: Bundle
          in: body
          description: Table information to be inserted
          required: true
          schema:
            $ref: '#/definitions/Bundle'
      tags:
        - Bundle
      responses:
        '201':
          description: Bundle has been created
          schema:
            $ref: '#/definitions/BundleResponse'
              
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

/ApiBundleTable/{bundleTableId}:
    get:
      description: |
        Gets a bundle
      description: |
        Retrieves a bundle table associated with the specific bundle ID
      parameters:
        - name: bundleId
          in: path
          description: bundle ID
          required: true
          
          format: integer
              
          responses:
          '200':
          description: A record with data filled
          schema:
            $ref: '#/definitions/Bundle'
          default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

/ApiBundleTableValues/{bundleTableId}/value:
    get:
      description: |
        Retrieves all values associated with the specific bundle table ID
      parameters:
        - name: bundleId
          in: path
          description: bundle ID
          required: true
          
          format: integer
      tags:
        - Bundle
      responses:
        '200':
          description: A bundle with data filled
          schema:
            $ref: '#/definitions/BundleValues'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

/ApiBundleContextless:
    post:
      description: |
        Creates a new bundle
      parameters:
        - name: Bundle
          in: body
          description: Table information to be inserted
          required: true
          schema:
            $ref: '#/definitions/BundleContextless'
          tags:
          - Bundle
          responses:
          '201':
          description: Bundle has been created
          schema:
            $ref: '#/definitions/BundleContextlessResponse'
              
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'

/ApiBundleContextlessValue/{bundleId}:
    get:
      description: |
        Retrieves the bundle associated with the specific bundle ID
        parameters:
        - name: bundleId
          in: path
          description: bundle ID
          required: true
          format: integer
        tags:
        - Bundle
        responses:
        '200':
          description: A bundle
          
            $ref: '#/definitions/BundleContextless'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

/ApiBundleContextlessValues/{bundleId}:
    get:
      description: |
        Retrieves all data associated with the specific bundle ID
      parameters:
        - name: bundleId
          in: path
          description: bundle ID
          required: true
          type: number
          format: integer
      tags:
        - Bundle
      responses:
        '200':
          description: A bundle with data filled
          schema:
            $ref: '#/definitions/BundleContextlessValues'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'



definitions:

  TimeStructure:
    properties:
      dateCreated:
        type: string
        format: date-time
        description: Time the entity was created
        example: "2015-08-16T21:45:22.551Z"
      lastUpdated:
        type: string
        format: date-time
        description: Time the entity was last updated
        example: "2015-08-16T21:45:22.551Z"
    required:
      - dateCreated
      - lastUpdated


BundleTable:
    required:
      - name
      - table
    properties:
      id:
        type: number
        format: int32
        description: Unique Table ID
        example: 1
      name:
        type: string
        description: Name of the table
        example: Location
      table:
        type: array
        description: table being used in bundle
        example: Facebook
      slices:
        type: string
        description: Name of the source
        example: "table id: { 4 name: event source: Facebook"
      conditions:
        type: array
        description: conditions put on slice
        example: event location 2
      data:
        type: array
        description: Bundle Data
        example: Facebook

BundleTableResponse:
    required:
      - name
    allOf:
    - $ref: '#/definitions/BundleTable'
    - $ref: '#/definitions/TimeStructure'
      
BundleTableValues:
    required:
      - bundleTableId
    allOf:
     - $ref: '#/definitions/TimeStructure'
     - properties:
        id:
          type: number
          description: Unique data value ID
        value:
          type: string
          description: An arbitrary data value to be stored
        fieldId:
          type: number
          description: Which field (column) the value is in
        recordId:
          type: number
          description: ID of the record the value is part of
          
  
    
BundleContextless:
    required:
      - name
      - tables
    properties:
      id:
        type: number
        format: int32
        description: Unique Bundle ID
        example: 1
      name:
        type: string
        description: Name of the bundle
        example: Location
      tables:
        type: string
        description: API bundle combination
        example: 
      
BundleContextlessValues:
    required:
      - bundleId
    properties:
        id:
          type: number
          description: bundleId
        organisationId:
          type: number
          description: ID of the table the Organisation is part of
        name:
          type: string
          description: name of the Organisation
    
BundleContextlessResponse:
    required:
      - name
    allOf:
    - $ref: '#/definitions/BundleContextless'
    - $ref: '#/definitions/TimeStructure'
        
Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string