name: Trivy Aqua

on:
  workflow_dispatch:
  # Uncomment when PR62 is merged
  # https://github.com/lazy-actions/gitrivy/pull/62
  # schedule:
  #   - cron: '0 4 * * MON'

env:
  REGISTRY: dataswift/hat  

jobs:
  trivy-scan:
    name: Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Container - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_DATASWIFT_USER }}
          password: ${{ secrets.DOCKERHUB_DATASWIFT_PASS }}

      - name: Container - Pull    
        run: docker pull ${{ env.REGISTRY }}:${{ github.sha }}

      - name: Container - Scan
        uses: lazy-actions/gitrivy@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REGISTRY }}:${{ github.sha }}
